// <auto-generated />
using Assignment5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Assignment5.Migrations
{
    [DbContext(typeof(DaintreeDBContext))]
    [Migration("20210304034633_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Assignment5.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<string>("Classification")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Publisher")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("BookID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Assignment5.Models.BookClassification", b =>
                {
                    b.Property<int>("BookID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassificationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BookID", "ClassificationID");

                    b.ToTable("BookClassifications");
                });

            modelBuilder.Entity("Assignment5.Models.Classification", b =>
                {
                    b.Property<int>("ClassificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassificationName")
                        .HasColumnType("TEXT");

                    b.HasKey("ClassificationID");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("BookClassification", b =>
                {
                    b.Property<int>("BooksBookID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassificationsClassificationID")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksBookID", "ClassificationsClassificationID");

                    b.HasIndex("ClassificationsClassificationID");

                    b.ToTable("BookClassification");
                });

            modelBuilder.Entity("BookClassification", b =>
                {
                    b.HasOne("Assignment5.Models.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assignment5.Models.Classification", null)
                        .WithMany()
                        .HasForeignKey("ClassificationsClassificationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
